### ISSUE TITLE
$fpm.system-dark-mode - make dark and light mode inactive

### ISSUE THREAD

**Issue by gsalunke** [FifthTry/ftd#159]
```ftd
--- ftd.image:
if: not $fpm.dark-mode
src: $light-mode-active

--- ftd.image: 
if: $fpm.dark-mode
src: $dark-mode-active

--- ftd.image:
if: $fpm.system-dark-mode
src: $system-mode-active
```
in above code - when we switch to `system-dark-mode` `dark-mode` also being active which shows dark mode and system mode icons both - can't we make only one mode active at a time?

**Comment by amitu** [comment]
I think this will be solved once https://github.com/FifthTry/ftd/issues/192 is implemented.
