### ISSUE TITLE
FTD - body ordered list not showing properly

### ISSUE THREAD

**Issue by gsalunke** [FifthTry/ftd#190]
While using below in `ftd` component list not generated properly, and all items coming as `1` number only

```ftd
-- ft.markdown:

1. Item number one
2. Item number two
```

**Comment by AviralVerma13** [comment]
This issue does not exist anymore. The following is rendered now for the above code now.
![image](https://user-images.githubusercontent.com/106665143/182723368-e7e747a6-e0cd-4c58-934b-2730bdc93897.png)
