### ISSUE TITLE
8 digit hexadecimal color code not working 

### ISSUE THREAD

**Issue by gsalunke** [FifthTry/ftd#212]
While using 8 digit color code below error is seen:

```
Processing fifthtry.github.io/button/index.ftd ... Error: PackageError { message: "failed to parse ParseError { message: \"#2cc9b566 is not a valid color: ColorParseError\", doc_id: \"fifthtry.github.io/button/\", line_number: 0 }" }
```
We should allow 8 digit hexadecimal color code:
```ftd
-- ftd.color main-text-color:
light: #2cc9b566
dark: #2cc9b566
```

**Comment by amitu** [comment]
This is because of https://github.com/7thSigil/css-color-parser-rs/issues/5. That issue is from 2018 with no commits in repo since ~5 yrs. Maybe we should fork it and try to implement it ourselves.
