### ISSUE TITLE
While switching from mobile to desktop  `spacing` is breaking

### ISSUE THREAD

**Issue by gsalunke** [FifthTry/ftd#236]
If I apply spacing to desktop view and I switch from desktop to mobile, vice-versa spacing gets removed on browser view. Attached images for more clarity of this issue!
<img width="508" alt="Screenshot 2022-06-22 at 5 01 58 PM" src="https://user-images.githubusercontent.com/68585007/175019065-569c8a32-811c-4593-8daa-6e00b1ea1ab8.png">

<img width="513" alt="Screenshot 2022-06-22 at 5 01 42 PM" src="https://user-images.githubusercontent.com/68585007/175019056-8b563d2f-35da-4fb4-86f4-e4e6c9c99556.png">

**Comment by amitu** [comment]
@gsalunke is this till happening?

**Comment by gsalunke** [comment]
@amitu yes this is fixed!

**Comment by amitu** [comment]
@gsalunke So close the issue. If you create an issue and its fixed, why is the issue still open?

**Comment by gsalunke** [comment]
@amitu if issue is fixed - someone should communicate!
