### ISSUE TITLE
Commented sections are getting processed as normal declarations.

### ISSUE THREAD

**Issue by AviralVerma13** [FifthTry/ftd#239]
The following piece of code gives error -
"ParseError { message: "foo is already declared", doc_id: "fail.ftd", line_number: 5 }"
even though the first one is commented.

```
/-- ftd.row foo:
caption name:
string list chapters:

-- ftd.column foo:
string name:

-- foo:
name: Arpita
```

**Comment by Heulitig** [comment]
This issue has been found in function "reorder()" in utils.rs and is resolved. We can go eat now.
