### ISSUE TITLE
Put check on Comments in one place

### ISSUE THREAD

**Issue by AviralVerma13** [FifthTry/ftd#244]
1. Checks on comment are on almost every file in "ftd"
2. Remove checks from all places and put it in one place.
3. The location should be just before "reorder" in "interpreter.rs", at which point it will ignore all the comments before reordering.

**Comment by amitu** [comment]
@AviralVerma13, @Heulitig status of this?

**Comment by Heulitig** [comment]
This is also done and merged.
Refer this PR - https://github.com/FifthTry/ftd/pull/245
