### ISSUE TITLE
`ftd.input` should support `defaultValue`

### ISSUE THREAD

**Issue by amitu** [FifthTry/ftd#255]
https://www.w3schools.com/jsref/prop_text_defaultvalue.asp

```ftd
-- ftd.input:
default-value: $foo
$on-input$: $foo=$VALUE
```

**Comment by amitu** [comment]
@Heulitig what is the status of this?

**Comment by Heulitig** [comment]
Yeah this is done and merged. 
Refer this PR - https://github.com/FifthTry/ftd/pull/258
