### ISSUE TITLE
ft.code shows unindented python code 

### ISSUE THREAD

**Issue by Heulitig** [FifthTry/ftd#322]
When we try to show some indented python code using ft.code. It shows the left aligned code.

```
-- ft.code:
lang: py

def foo():
     s = "foo"
     for i in range(10):
           print(s)
```

Above code will show this output: 
![issue](https://user-images.githubusercontent.com/106665190/182102573-0bb74335-a86e-41c9-ad3e-aa3f0d72cdad.png)

**Comment by AviralVerma13** [comment]
In the latest ftd, this issue does not exist. Checked.

![image](https://user-images.githubusercontent.com/106665143/182726288-cba95b77-fdae-4c1c-b84d-23175c1057bd.png)
