### ISSUE TITLE
Wrong line number on error messages when auto-imports are used

### ISSUE THREAD

**Issue by amitu** [FifthTry/ftd#377]
### [Discussion](https://github.com/FifthTry/ftd/discussions/335)

<div type='discussions-op-text'>

<sup>Originally posted by **Heulitig** August  7, 2022</sup>
Currently, when we use `auto-imports`, a `prefixed document` is generated before passing it to ftd. `Ftd` receives this prefixed document instead of the actual document and since the actual document contents are shifted down that's why we are getting wrong line number on the error messages.
 
```markdown
Prefixed Body: {Auto-imports}\n\n{Actual document}  
Shift in line number = (no of auto-imports used + 2)
```
Need some way to fix this line number issue by sending this data regarding auto-imports separately and avoid altering the original line numbers of the document.

# How To Solve This?

Simplest solution would be to pass both document source and `offset` when we are continuing after [continue_after_import ](https://github.com/FifthTry/ftd/blob/main/src/p2/interpreter.rs#L577).

```rust
fn continue_after_import(mut self, id: &str, source: &str, offset: usize) -> ftd::p1::Result<Interpreter>
```

Then whenever ftd is printing, it will print `line-number - offset` as line number. 

Problem with this approach: What if file corresponding to auto import does not exist or has an issue during import?</div>

**Comment by AviralVerma13** [comment]
This issue was earlier raised, though not in detail.  refer https://github.com/FifthTry/ftd/issues/230

**Comment by amitu** [comment]
Closing it as duplicate of https://github.com/FifthTry/ftd/issues/230.
