### ISSUE TITLE
email text color not changing - always blue 

### ISSUE THREAD

**Issue by gsalunke** [FifthTry/ftd#62]
![email-blue-color](https://user-images.githubusercontent.com/68585007/148720286-d50dba29-1212-4b86-9f61-8c2191414d47.PNG)
```
-- ftd.text author-email: $title
caption title:
color if $fpm-ui.dark-mode: #BFBFBF
color: #000000
size: 24
line-height: 28
align: left
font: Itim
```
though in above code color is mentioned still it takes default blue color for email! check attached output screen-grab

**Comment by amitu** [comment]
Will be implemented with #101 is implemented.
